### ISSUE TITLE
Can't use keyboard on iOS

### ISSUE THREAD

**Issue by dwerg85** [KenLPham/F1-AppleTV#1]
**Issue**
When you need to enter the username and password and you get the option to use your phone's keyboard it doesn't really accept input. 
What happens is that it sort of stays stuck on one character and discards all the rest. 

**Steps to reproduce** 
Open app and get to the log in screen. 
Open iOS device and select the option to use keyboard on device. 
Type credential. 

**Expected behavior**
Being able to properly input credentials from keyboard on iOS device

**Comment by KenLPham** [comment]
keyboard input works fine using the Remote app but is bugged from Control Center remote

**Comment by KenLPham** [comment]
Testing on new Apple TV running tvOS 14.7 and on iOS 14.7.1. This doesn't seem to be an issue with the latest update (#13 ). Closing
