### ISSUE TITLE
Video streams stopped working

### ISSUE THREAD

**Issue by dwerg85** [KenLPham/F1-AppleTV#10]
Maybe this is the same issue the other apps were having a while back, but none of the streams are working anymore in the app. 

All the menus work, so you can see what is live and what isn't. But once you select a stream to watch, you only get the background and nothing else.

**Comment by KenLPham** [comment]
I just tested it from the latest commit and was able to load the stream fine. Are you talking about the livestream or archive streams?

**Comment by dwerg85** [comment]
Tried again with the new files and at first it didn't want to work (see this vid: http://wakbopidakos.com/F1TV/IMGF1TV.mov)
But then after login out and in again, and then messing around with a version in the simulator it suddenly started working on the aTV. So not sure what's up there.

**Comment by KenLPham** [comment]
weird. I'll add some error handling when i can so that it'll display errors (if any) on screen to try and figure this out

**Comment by KenLPham** [comment]
Not reproducible. App has been updated #13 so this might have been fixed. Reopen if the issue still persists
