### ISSUE TITLE
ipa release

### ISSUE THREAD

**Issue by sasagr** [KenLPham/F1-AppleTV#18]
Would it be possible to have ipa released that can be signed by the user?
I have an old Xcode (<13) and I cannot buld it from source.

**Comment by KenLPham** [comment]
Sure! Will do that once i solve #17

**Comment by KenLPham** [comment]
GitHub Action created to build IPA https://github.com/KenLPham/F1-AppleTV/releases/tag/2.0.2

I haven't tried signing it myself, but let me know if it works!

**Comment by sasagr** [comment]
you must have missed something... the ipa (only 166 Bytes) is an empty containers. The Payload folder is empty.

**Comment by KenLPham** [comment]
yup.. forgot to recursively zip the payload file. Should be a valid IPA now

**Comment by sasagr** [comment]
Works great. Thanks!
