### ISSUE TITLE
Live stream doesn't play

### ISSUE THREAD

**Issue by dwerg85** [KenLPham/F1-AppleTV#2]
**Issue**
In general when you open a stream it shows a frame and shows the loading animation. On streams that aren't life you can get the stream to play by pressing the play button. On the life stream trying to do this results (when I tested it during the Italian qualy) in  a GT3 series stream coming up instead. 

**Steps to reproduce**
Log it.
Select the race weekend set.
Select the 'Live' session. 
Select the Main Feed. 

**Expected behavior**
Stream plays when selected without having to press play again (and get the proper stream).

**Comment by dwerg85** [comment]
Alright, clicked around a bit more. Seems that if I double click play on the life stream and then press play again I'll get the proper stream to play. If I press play once, the GT3 stream plays.

**Comment by KenLPham** [comment]
Fixed stream not starting, just forgot to actually start the video. 
For incorrect stream, not sure if fixed, would have to try it on a race weekend to make sure.

**Comment by dwerg85** [comment]
Stream plays when opened and now also fills the whole screen. 
I'll try to test the stream coming weekend for the livestream issue.

**Comment by dwerg85** [comment]
Worked great during FP1 and Qualy. Full screen and correct stream showing and playing.
