### ISSUE TITLE
Screensaver isn't suppressed

### ISSUE THREAD

**Issue by dwerg85** [KenLPham/F1-AppleTV#3]
**Issue**
When playing a stream and not giving other input the AppleTV will drop into the screensaver.

**Steps to reproduce**
Log in, navigate to stream, play stream. Leave stream on and eventually the stream will stop and the screensaver will show.

**Expected behavior**
Screensaver is not activated while video is playing.

**Comment by KenLPham** [comment]
Should be fixed in latest update. Can't test it on the simulator so would need feedback on if the changes worked

**Comment by dwerg85** [comment]
Had it playing for nearly 13 mins without touching it. No screensaver. Looks like it's fixed. Closing the issue.
