### ISSUE TITLE
FLOSS Licenses and Apple

### ISSUE THREAD

**Issue by anthonylavado** [KenLPham/F1-AppleTV#9]
Hey there!
Love the look of this and I plan to check it out later on my Apple TV. One big heads up though - stuff with the GPL License is technically not compatible with the App Store's distribution.

While this shouldn't really be an issue so far (since you're the only committer of code, and it doesn't seem like you've pulled in any other modules from elsewhere), it may be an issue later on if you start accepting outside contributions of code. In essence, when you publish the app on the store, it modifies the package to have a "purchase" restriction, even if the app is free. That's the part that breaks GPL "compatibility".

Since you're the sole copyright holder so far, if you do decide to publish it on the App Store, you essentially grant Apple a separate license to distribute the app on their terms. This isn't a formal process, it's just something you note this to yourself personally. If other contributions come up, then it gets tricky - you have to get every contributor to agree to the same license, or else you can't change it 😄

It's for this reason that over at https://github.com/jellyfin/jellyfin-expo we decided to use the [MPL 2.0](https://choosealicense.com/licenses/mpl-2.0/) for our license, which is also what VLC for iOS/tvOS uses.

If you have any questions, let me know. After nearly two years of managing app releases for Jellyfin, I've learned more than I cared to about this...

**Comment by KenLPham** [comment]
Thanks for letting me know. I decided to use GPL since it was the one [f1viewer](https://github.com/SoMuchForSubtlety/f1viewer/blob/master/LICENSE) uses and I used their source code to port the F1 API, but since I didn't directly use any code, I'm assuming I could just change the license without issue?

At the moment, I don't plan on submitting this app to the App Store as [a previous attempt](https://github.com/MarkusTheOrt/F1TVUnofficial) wasn't approved.

**Comment by dwerg85** [comment]
> At the moment, I don't plan on submitting this app to the App Store as a previous attempt wasn't approved.

I was thinking about this the other day. I wonder if you stripped the app of any and all F1 IP (called the app Super Fast Racing Stream Watcher or something), other colors and all that if it might get accepted. You'd have to submit it using some other dev account to not jeopardize whichever other apps you may have in the store I guess. But might be worth a try.

**Comment by KenLPham** [comment]
paying $100 for a new developer account for the hope that trying to get around Ostmodern or FOM's approval doesn't seem worth it imo. If someone else wants to try, they can. Just add me as a developer or something.

**Comment by dwerg85** [comment]
Nah you're right. I totally forgot that it's not a risk free exercise on the end of the submitter.
